#!/usr/bin/python3
import os
import _thread
import time
	os.system("clear")
# Define a function for the thread
target=input("TARGET: ")
def print_time( threadName, delay):
	count = 0
	while count < 5:
		time.sleep(.0)
		os.system('ping ' + target)
		time.sleep(.0)
try:
   _thread.start_new_thread( print_time, ("Thread-1", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-2", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-3", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-4", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-5", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-6", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-7", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-8", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-9", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-10", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-11", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-12", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-13", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-14", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-15", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-16", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-17", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-18", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-19", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-20", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-21", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-22", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-23", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-24", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-25", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-26", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-27", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-28", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-29", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-30", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-31", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-32", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-33", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-34", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-35", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-36", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-37", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-38", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-39", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-40", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-41", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-42", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-43", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-44", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-45", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-46", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-47", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-48", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-49", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-50", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-51", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-52", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-53", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-54", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-55", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-56", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-57", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-58", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-59", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-60", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-61", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-62", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-63", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-64", 1, ) )
   _thread.start_new_thread( print_time, ("Thread-65", 1, ) )
except:
   print("Error. Thread Cannot Be Opened. Trying Again")

while 1:
   pass